name: Run Oracle Grabber

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: curl, mbstring, openssl

      - name: Install Dependencies
        run: composer install

      - name: Create Env File
        run: |
          cat <<EOF > .env
          OCI_USER_ID="${{ secrets.OCI_USER_ID }}"
          OCI_TENANCY_ID="${{ secrets.OCI_TENANCY_ID }}"
          OCI_FINGERPRINT="${{ secrets.OCI_FINGERPRINT }}"
          OCI_REGION="${{ secrets.OCI_REGION }}"
          OCI_SUBNET_ID="${{ secrets.OCI_SUBNET_ID }}"
          OCI_PRIVATE_KEY="${{ secrets.OCI_PRIVATE_KEY }}"
          EOF

      - name: Run Grabber
        run: php index.php
